version: "2.4"

services:
  movieshop:
    image: movieshop:0.0.1
    ports:
      - 8080:8080
    environment:
      DB_URL: "jdbc:h2:tcp://h2db/movieshop-db;DB_CLOSE_DELAY=-1"
      DB_USERNAME: "fcinar"
      DB_PASSWORD: "123456"

  h2db:
    image: buildo/h2database
    ports:
      - 9090:8082